// crates/cli/src/config.rs
// Persistent CLI configuration stored at ~/.creg/config.toml.
// Values here are the defaults — any flag passed on the command line takes precedence.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CliConfig {
    /// Primary chain node URL.
    #[serde(default = "default_node_url")]
    pub node_url: String,

    /// Fallback node URLs tried in order if the primary is unreachable.
    #[serde(default)]
    pub fallback_nodes: Vec<String>,

    /// Ecosystem to assume when none can be auto-detected.
    #[serde(default = "default_ecosystem")]
    pub default_ecosystem: String,

    /// Whether to run in strict mode (fail on unverified, not just revoked).
    #[serde(default)]
    pub strict: bool,

    /// Whether to use light-client SPV verification on every install.
    #[serde(default)]
    pub use_light_client: bool,

    /// Whether to write pkg-lock.chain audit receipts after every install.
    #[serde(default = "default_true")]
    pub write_lockfile: bool,

    /// Path to the publisher private key file.
    pub publisher_key: Option<String>,

    /// Path to a checkpoint JSON file for light-client verification.
    pub checkpoint_file: Option<String>,

    /// EVM RPC URL for staking transactions.
    pub rpc_url: Option<String>,

    /// Staking contract address.
    pub staking_address: Option<String>,

    /// Suppress verified-package output during install (only show warnings/errors).
    #[serde(default = "default_true")]
    pub quiet_on_verified: bool,
}

impl Default for CliConfig {
    fn default() -> Self {
        Self {
            node_url:          default_node_url(),
            fallback_nodes:    vec![],
            default_ecosystem: default_ecosystem(),
            strict:            false,
            use_light_client:  false,
            write_lockfile:    true,
            publisher_key:     None,
            checkpoint_file:   None,
            rpc_url:           None,
            staking_address:   None,
            quiet_on_verified: true,
        }
    }
}

fn default_node_url()   -> String { "http://localhost:8080".into() }
fn default_ecosystem()  -> String { "npm".into() }
fn default_true()       -> bool   { true }

impl CliConfig {
    /// Load from the config file, returning defaults if the file doesn't exist.
    pub fn load() -> Result<Self> {
        let path = config_path();
        if !path.exists() {
            return Ok(Self::default());
        }
        let raw = std::fs::read_to_string(&path)
            .with_context(|| format!("Cannot read config file: {}", path.display()))?;
        let config: Self = toml::from_str(&raw)
            .with_context(|| format!("Invalid config file: {}", path.display()))?;
        Ok(config)
    }

    /// Save the current config to disk.
    pub fn save(&self) -> Result<()> {
        let path = config_path();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let raw = toml::to_string_pretty(self)
            .context("Failed to serialise config")?;
        let with_header = format!(
            "# chain-registry CLI configuration\n# Generated by creg config\n# See: creg config --help\n\n{}",
            raw
        );
        std::fs::write(&path, with_header)
            .with_context(|| format!("Cannot write config file: {}", path.display()))?;
        Ok(())
    }

    /// Resolve the effective node URL: env var > flag > config file > default.
    pub fn effective_node_url(&self, flag: Option<&str>) -> String {
        if let Some(f) = flag { return f.to_string(); }
        if let Ok(env) = std::env::var("CREG_NODE_URL") { return env; }
        self.node_url.clone()
    }

    /// Print the current config in a human-readable table.
    pub fn print(&self) {
        let path = config_path();
        println!("\n  Config file: {}\n", path.display());
        println!("  {:<24} {}", "node_url",          self.node_url);
        println!("  {:<24} {}", "default_ecosystem",  self.default_ecosystem);
        println!("  {:<24} {}", "strict",             self.strict);
        println!("  {:<24} {}", "use_light_client",   self.use_light_client);
        println!("  {:<24} {}", "write_lockfile",      self.write_lockfile);
        println!("  {:<24} {}", "quiet_on_verified",  self.quiet_on_verified);
        if let Some(ref k) = self.publisher_key {
            println!("  {:<24} {}", "publisher_key", k);
        }
        if let Some(ref r) = self.rpc_url {
            println!("  {:<24} {}", "rpc_url", r);
        }
        if !self.fallback_nodes.is_empty() {
            println!("  {:<24} {}", "fallback_nodes", self.fallback_nodes.join(", "));
        }
        println!();
    }
}

fn config_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".creg")
        .join("config.toml")
}

/// Interactive `creg config set KEY VALUE` handler.
pub fn set_value(key: &str, value: &str) -> Result<()> {
    let mut cfg = CliConfig::load()?;

    match key {
        "node_url"          => cfg.node_url          = value.to_string(),
        "default_ecosystem" => cfg.default_ecosystem = value.to_string(),
        "strict"            => cfg.strict            = parse_bool(value)?,
        "use_light_client"  => cfg.use_light_client  = parse_bool(value)?,
        "write_lockfile"    => cfg.write_lockfile     = parse_bool(value)?,
        "quiet_on_verified" => cfg.quiet_on_verified  = parse_bool(value)?,
        "publisher_key"     => cfg.publisher_key      = Some(value.to_string()),
        "checkpoint_file"   => cfg.checkpoint_file    = Some(value.to_string()),
        "rpc_url"           => cfg.rpc_url            = Some(value.to_string()),
        "staking_address"   => cfg.staking_address    = Some(value.to_string()),
        other => anyhow::bail!(
            "Unknown config key '{}'. Valid keys: node_url, default_ecosystem, \
             strict, use_light_client, write_lockfile, quiet_on_verified, \
             publisher_key, checkpoint_file, rpc_url, staking_address",
            other
        ),
    }

    cfg.save()?;
    println!("  ✓ Set {} = {}", key, value);
    Ok(())
}

fn parse_bool(s: &str) -> Result<bool> {
    match s.to_lowercase().as_str() {
        "true" | "yes" | "1" | "on"  => Ok(true),
        "false" | "no" | "0" | "off" => Ok(false),
        _ => anyhow::bail!("Expected true/false, got '{}'", s),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn default_config_serializes() {
        let cfg = CliConfig::default();
        let raw = toml::to_string_pretty(&cfg).unwrap();
        assert!(raw.contains("node_url"));
    }

    #[test]
    fn parse_bool_handles_variants() {
        assert!(parse_bool("true").unwrap());
        assert!(parse_bool("yes").unwrap());
        assert!(parse_bool("1").unwrap());
        assert!(!parse_bool("false").unwrap());
        assert!(!parse_bool("no").unwrap());
        assert!(parse_bool("maybe").is_err());
    }
}
