// crates/cli/src/sbom.rs
// `creg sbom <package> [--format spdx|cyclonedx]` — SBOM export.
//
// Generates a Software Bill of Materials (SBOM) for a chain-registered package
// in SPDX 2.3 (JSON) or CycloneDX 1.4 (JSON) format.

use anyhow::{Context, Result};
use chrono::Utc;
use colored::Colorize;

#[derive(Debug, Clone, Copy)]
pub enum SbomFormat {
    Spdx,
    CycloneDx,
}

impl std::str::FromStr for SbomFormat {
    type Err = anyhow::Error;
    fn from_str(s: &str) -> Result<Self> {
        match s.to_lowercase().as_str() {
            "spdx" => Ok(SbomFormat::Spdx),
            "cyclonedx" | "cdx" => Ok(SbomFormat::CycloneDx),
            _ => anyhow::bail!("Unknown SBOM format: '{}'. Use 'spdx' or 'cyclonedx'.", s),
        }
    }
}

pub async fn run(
    package: &str,
    ecosystem: Option<&str>,
    format: SbomFormat,
    output: Option<&std::path::Path>,
    node_url: Option<&str>,
) -> Result<()> {
    let base = node_url.map(String::from).unwrap_or_else(|| {
        std::env::var("CREG_NODE_URL").unwrap_or_else(|_| "http://localhost:8080".into())
    });

    let canonical = if package.contains(':') {
        package.to_string()
    } else {
        let eco = ecosystem.unwrap_or("npm");
        let (name, ver) = if let Some(idx) = package.rfind('@') {
            (&package[..idx], &package[idx + 1..])
        } else {
            (package, "latest")
        };
        format!("{}:{}@{}", eco, name, ver)
    };

    println!(
        "{} Generating SBOM for {} ...",
        "→".cyan(),
        canonical.bold()
    );

    let encoded = urlencoding::encode(&canonical);
    let url = format!("{}/v1/packages/{}", base.trim_end_matches('/'), encoded);

    let resp = reqwest::Client::new()
        .get(&url)
        .timeout(std::time::Duration::from_secs(10))
        .send()
        .await
        .context("Failed to reach registry node")?;

    if !resp.status().is_success() {
        anyhow::bail!("Package '{}' not found (HTTP {})", canonical, resp.status());
    }

    let record: serde_json::Value = resp
        .json()
        .await
        .context("Failed to parse package record")?;

    let sbom_doc = match format {
        SbomFormat::Spdx => generate_spdx(&canonical, &record)?,
        SbomFormat::CycloneDx => generate_cyclonedx(&canonical, &record)?,
    };

    let pretty = serde_json::to_string_pretty(&sbom_doc)?;

    if let Some(path) = output {
        std::fs::write(path, &pretty)
            .with_context(|| format!("Failed to write SBOM to {}", path.display()))?;
        println!("{} SBOM saved to {}", "✓".green(), path.display());
    } else {
        println!("{}", pretty);
    }

    Ok(())
}

fn generate_spdx(canonical: &str, record: &serde_json::Value) -> Result<serde_json::Value> {
    let content_hash = record
        .get("content_hash")
        .and_then(|v| v.as_str())
        .unwrap_or("");
    let publisher = record
        .get("publisher")
        .and_then(|v| v.as_str())
        .unwrap_or("unknown");
    let status = record
        .get("status")
        .and_then(|v| v.as_str())
        .unwrap_or("unknown");
    let published_at = record
        .get("published_at")
        .and_then(|v| v.as_str())
        .unwrap_or("");
    let ipfs_cid = record
        .get("ipfs_cid")
        .and_then(|v| v.as_str())
        .unwrap_or("");

    // Parse canonical → name + version
    let (name, version) = parse_canonical(canonical);

    let doc_namespace = format!(
        "https://chain-registry.io/sbom/{}/{}",
        canonical,
        Utc::now().timestamp()
    );

    Ok(serde_json::json!({
        "spdxVersion": "SPDX-2.3",
        "dataLicense": "CC0-1.0",
        "SPDXID": "SPDXRef-DOCUMENT",
        "name": format!("{}-sbom", name),
        "documentNamespace": doc_namespace,
        "creationInfo": {
            "created": Utc::now().to_rfc3339(),
            "creators": [
                format!("Tool: creg/chain-registry"),
                format!("Organization: Chain Registry"),
            ],
            "comment": "Generated by creg sbom"
        },
        "packages": [{
            "SPDXID": "SPDXRef-Package",
            "name": name,
            "version": version,
            "downloadLocation": format!("ipfs://{}", ipfs_cid),
            "filesAnalyzed": false,
            "checksums": [{
                "algorithm": "SHA256",
                "checksumValue": content_hash,
            }],
            "supplier": format!("Organization: {}", &publisher[..publisher.len().min(16)]),
            "originator": format!("Organization: {}", &publisher[..publisher.len().min(16)]),
            "primaryPackagePurpose": "LIBRARY",
            "externalRefs": [
                {
                    "referenceCategory": "PACKAGE-MANAGER",
                    "referenceType": "chain-registry",
                    "referenceLocator": canonical,
                },
                {
                    "referenceCategory": "OTHER",
                    "referenceType": "verification-status",
                    "referenceLocator": format!("status:{}", status),
                }
            ],
            "annotations": [
                {
                    "annotationType": "OTHER",
                    "annotator": format!("Tool: creg"),
                    "annotationDate": Utc::now().to_rfc3339(),
                    "comment": format!("Published at: {}; Chain status: {}", published_at, status),
                }
            ]
        }],
        "relationships": [{
            "spdxElementId": "SPDXRef-DOCUMENT",
            "relationshipType": "DESCRIBES",
            "relatedSpdxElement": "SPDXRef-Package"
        }]
    }))
}

fn generate_cyclonedx(canonical: &str, record: &serde_json::Value) -> Result<serde_json::Value> {
    let content_hash = record
        .get("content_hash")
        .and_then(|v| v.as_str())
        .unwrap_or("");
    let publisher = record
        .get("publisher")
        .and_then(|v| v.as_str())
        .unwrap_or("unknown");
    let status = record
        .get("status")
        .and_then(|v| v.as_str())
        .unwrap_or("unknown");
    let published_at = record
        .get("published_at")
        .and_then(|v| v.as_str())
        .unwrap_or("");
    let ipfs_cid = record
        .get("ipfs_cid")
        .and_then(|v| v.as_str())
        .unwrap_or("");

    let (name, version) = parse_canonical(canonical);
    let bom_ref = format!("pkg:chain-registry/{}/{}", name, version);

    Ok(serde_json::json!({
        "bomFormat": "CycloneDX",
        "specVersion": "1.4",
        "serialNumber": format!("urn:uuid:{}", uuid_from_canonical(canonical)),
        "version": 1,
        "metadata": {
            "timestamp": Utc::now().to_rfc3339(),
            "tools": [{ "vendor": "Chain Registry", "name": "creg", "version": "0.1.0" }]
        },
        "components": [{
            "type": "library",
            "bom-ref": bom_ref,
            "name": name,
            "version": version,
            "purl": format!("pkg:{}@{}", canonical.replace(':', "/"), ""),
            "hashes": [{ "alg": "SHA-256", "content": content_hash }],
            "externalReferences": [
                {
                    "type": "distribution",
                    "url": format!("ipfs://{}", ipfs_cid),
                    "comment": "IPFS content address"
                }
            ],
            "properties": [
                { "name": "chain-registry:status",       "value": status },
                { "name": "chain-registry:published_at", "value": published_at },
                { "name": "chain-registry:publisher",    "value": &publisher[..publisher.len().min(20)] },
                { "name": "chain-registry:canonical",    "value": canonical },
            ]
        }]
    }))
}

fn parse_canonical(canonical: &str) -> (String, String) {
    // canonical format: ecosystem:name@version
    let without_eco = canonical.split(':').nth(1).unwrap_or(canonical);
    if let Some(idx) = without_eco.rfind('@') {
        (
            without_eco[..idx].to_string(),
            without_eco[idx + 1..].to_string(),
        )
    } else {
        (without_eco.to_string(), "unknown".to_string())
    }
}

/// Deterministic pseudo-UUID from canonical string (no rand dependency needed).
fn uuid_from_canonical(canonical: &str) -> String {
    use std::hash::{Hash, Hasher};
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    canonical.hash(&mut hasher);
    let h = hasher.finish();
    format!("{:016x}-0000-4000-8000-000000000000", h)
}
