// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title ZKSlashingVerifier
 * @notice Verifies zero-knowledge proofs for slashing evidence
 * @dev Uses Groth16 proofs generated by Circom circuits
 * 
 * This contract allows permissionless verification of validator offenses,
 * eliminating the need for validator voting on slashing decisions.
 */
contract ZKSlashingVerifier {
    
    // ============ Errors ============
    
    error InvalidProof();
    error ProofAlreadyUsed(bytes32 nullifier);
    error InvalidVerifyingKey();
    error UnauthorizedKeyUpdate();
    
    // ============ Types ============
    
    /// @notice Groth16 proof structure
    struct Proof {
        uint256[2] a;
        uint256[2][2] b;
        uint256[2] c;
    }
    
    /// @notice Types of slashing evidence
    enum EvidenceType {
        DoubleSign,      // Conflicting votes on same package
        FalseApproval,   // Approved malicious package
        Griefing         // Consistently voting against majority
    }
    
    /// @notice Verifying key for a proof type
    struct VerifyingKey {
        uint256[2] alpha1;
        uint256[2][2] beta2;
        uint256[2][2] gamma2;
        uint256[2][2] delta2;
        uint256[2][] ic;
    }
    
    // ============ State ============
    
    /// @notice Owner who can update verifying keys
    address public owner;
    
    /// @notice Used nullifiers to prevent replay attacks
    mapping(bytes32 => bool) public usedNullifiers;
    
    /// @notice Verifying keys for each evidence type
    mapping(EvidenceType => VerifyingKey) internal verifyingKeys;
    
    /// @notice Number of public inputs expected for each type
    mapping(EvidenceType => uint256) public publicInputCounts;
    
    /// @notice Total proofs verified
    uint256 public totalProofsVerified;
    
    // ============ Events ============
    
    event ProofVerified(
        EvidenceType indexed evidenceType,
        bytes32 indexed nullifier,
        address indexed verifier
    );
    
    event VerifyingKeyUpdated(
        EvidenceType indexed evidenceType,
        address indexed updater
    );
    
    event OwnershipTransferred(
        address indexed previousOwner,
        address indexed newOwner
    );
    
    // ============ Modifiers ============
    
    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }
    
    // ============ Constructor ============
    
    constructor() {
        owner = msg.sender;
        
        // Initialize public input counts
        publicInputCounts[EvidenceType.DoubleSign] = 5;
        publicInputCounts[EvidenceType.FalseApproval] = 4;
        publicInputCounts[EvidenceType.Griefing] = 3;
    }
    
    // ============ External Functions ============
    
    /**
     * @notice Verify a double-sign proof
     * @param proof Groth16 proof
     * @param publicInputs [validatorPubkeyX, validatorPubkeyY, packageHash, vote1Hash, vote2Hash]
     * @return valid Whether proof is valid
     * @return nullifier Unique nullifier for this proof
     */
    function verifyDoubleSign(
        Proof calldata proof,
        uint256[5] calldata publicInputs
    ) external returns (bool valid, bytes32 nullifier) {
        // Compute nullifier
        nullifier = keccak256(abi.encodePacked(publicInputs));
        
        // Check not already used
        if (usedNullifiers[nullifier]) {
            revert ProofAlreadyUsed(nullifier);
        }
        
        // Build input array for verification
        uint256[] memory inputs = new uint256[](5);
        for (uint256 i = 0; i < 5; i++) {
            inputs[i] = publicInputs[i];
        }
        
        // Verify proof
        valid = _verifyProof(EvidenceType.DoubleSign, proof, inputs);
        
        if (!valid) {
            revert InvalidProof();
        }
        
        // Mark nullifier as used
        usedNullifiers[nullifier] = true;
        totalProofsVerified++;
        
        emit ProofVerified(EvidenceType.DoubleSign, nullifier, msg.sender);
        
        return (valid, nullifier);
    }
    
    /**
     * @notice Verify a false approval proof
     * @param proof Groth16 proof
     * @param publicInputs [validatorPubkey, packageHash, approvalTimestamp, revocationTimestamp]
     * @return valid Whether proof is valid
     * @return nullifier Unique nullifier for this proof
     */
    function verifyFalseApproval(
        Proof calldata proof,
        uint256[4] calldata publicInputs
    ) external returns (bool valid, bytes32 nullifier) {
        nullifier = keccak256(abi.encodePacked(publicInputs));
        
        if (usedNullifiers[nullifier]) {
            revert ProofAlreadyUsed(nullifier);
        }
        
        uint256[] memory inputs = new uint256[](4);
        for (uint256 i = 0; i < 4; i++) {
            inputs[i] = publicInputs[i];
        }
        
        valid = _verifyProof(EvidenceType.FalseApproval, proof, inputs);
        
        if (!valid) revert InvalidProof();
        
        usedNullifiers[nullifier] = true;
        totalProofsVerified++;
        
        emit ProofVerified(EvidenceType.FalseApproval, nullifier, msg.sender);
        
        return (valid, nullifier);
    }
    
    /**
     * @notice Verify a griefing proof
     * @param proof Groth16 proof
     * @param publicInputs [validatorPubkey, voteHistoryHash, disagreementRate]
     * @return valid Whether proof is valid
     * @return nullifier Unique nullifier for this proof
     */
    function verifyGriefing(
        Proof calldata proof,
        uint256[3] calldata publicInputs
    ) external returns (bool valid, bytes32 nullifier) {
        nullifier = keccak256(abi.encodePacked(publicInputs));
        
        if (usedNullifiers[nullifier]) {
            revert ProofAlreadyUsed(nullifier);
        }
        
        uint256[] memory inputs = new uint256[](3);
        for (uint256 i = 0; i < 3; i++) {
            inputs[i] = publicInputs[i];
        }
        
        valid = _verifyProof(EvidenceType.Griefing, proof, inputs);
        
        if (!valid) revert InvalidProof();
        
        usedNullifiers[nullifier] = true;
        totalProofsVerified++;
        
        emit ProofVerified(EvidenceType.Griefing, nullifier, msg.sender);
        
        return (valid, nullifier);
    }
    
    /**
     * @notice Set the verifying key for an evidence type
     * @param evidenceType Type of evidence
     * @param vk Verifying key
     */
    function setVerifyingKey(
        EvidenceType evidenceType,
        VerifyingKey calldata vk
    ) external onlyOwner {
        if (vk.ic.length == 0) revert InvalidVerifyingKey();
        
        verifyingKeys[evidenceType] = vk;
        
        emit VerifyingKeyUpdated(evidenceType, msg.sender);
    }
    
    /**
     * @notice Transfer ownership
     * @param newOwner New owner address
     */
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Invalid address");
        
        address oldOwner = owner;
        owner = newOwner;
        
        emit OwnershipTransferred(oldOwner, newOwner);
    }
    
    /**
     * @notice Check if a nullifier has been used
     * @param nullifier Nullifier to check
     */
    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return usedNullifiers[nullifier];
    }
    
    // ============ Internal Functions ============
    
    /**
     * @notice Internal proof verification using BN254 precompile pairing check
     * @param evidenceType Type of evidence
     * @param proof Groth16 proof
     * @param inputs Public inputs
     * @return valid Whether proof is valid
     */
    function _verifyProof(
        EvidenceType evidenceType,
        Proof calldata proof,
        uint256[] memory inputs
    ) internal view returns (bool valid) {
        VerifyingKey storage vk = verifyingKeys[evidenceType];
        
        // Check that vk is set
        if (vk.ic.length == 0) return false;
        require(inputs.length + 1 == vk.ic.length, "Invalid input length");

        // 1) Compute the linear combination:  vk_x = vk.ic[0] + sum(inputs[i] * vk.ic[i+1])
        uint256[2] memory vk_x;
        vk_x[0] = vk.ic[0][0];
        vk_x[1] = vk.ic[0][1];

        for (uint256 i = 0; i < inputs.length; i++) {
            uint256[2] memory s = _ecMul(vk.ic[i + 1], inputs[i]);
            vk_x = _ecAdd(vk_x, s);
        }

        // 2) Build the pairing input for the BN256Pairing precompile (0x08).
        //    We need to check:
        //      e(-A, B) · e(vk.alpha1, vk.beta2) · e(vk_x, vk.gamma2) · e(C, vk.delta2) == 1
        //    which is equivalent to:
        //      e(A, B) == e(vk.alpha1, vk.beta2) · e(vk_x, vk.gamma2) · e(C, vk.delta2)
        //
        //    We negate proof.a (the first G1 point).
        uint256[2] memory negA = _negateG1(proof.a);

        // Encode 4 pairing pairs: each pair is (G1_x, G1_y, G2_x_im, G2_x_re, G2_y_im, G2_y_re)
        // = 4 * 6 = 24 uint256 words
        uint256[24] memory input;

        // Pair 1: (-A, B)
        input[0]  = negA[0];
        input[1]  = negA[1];
        input[2]  = proof.b[0][0];
        input[3]  = proof.b[0][1];
        input[4]  = proof.b[1][0];
        input[5]  = proof.b[1][1];

        // Pair 2: (alpha1, beta2)
        input[6]  = vk.alpha1[0];
        input[7]  = vk.alpha1[1];
        input[8]  = vk.beta2[0][0];
        input[9]  = vk.beta2[0][1];
        input[10] = vk.beta2[1][0];
        input[11] = vk.beta2[1][1];

        // Pair 3: (vk_x, gamma2)
        input[12] = vk_x[0];
        input[13] = vk_x[1];
        input[14] = vk.gamma2[0][0];
        input[15] = vk.gamma2[0][1];
        input[16] = vk.gamma2[1][0];
        input[17] = vk.gamma2[1][1];

        // Pair 4: (C, delta2)
        input[18] = proof.c[0];
        input[19] = proof.c[1];
        input[20] = vk.delta2[0][0];
        input[21] = vk.delta2[0][1];
        input[22] = vk.delta2[1][0];
        input[23] = vk.delta2[1][1];

        uint256[1] memory out;
        bool success;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            // precompile 0x08 = bn256Pairing
            // input:  24 * 32 = 768 bytes
            // output: 32 bytes (0 or 1)
            success := staticcall(gas(), 0x08, input, 768, out, 32)
        }
        return success && out[0] == 1;
    }
    
    // ============ BN254 Precompile Helpers ============

    /// @notice Negate a G1 point (reflects y over the BN254 field prime)
    function _negateG1(uint256[2] memory p) internal pure returns (uint256[2] memory) {
        // BN254 field prime
        uint256 q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        if (p[0] == 0 && p[1] == 0) return p;
        return [p[0], q - (p[1] % q)];
    }

    /// @notice BN254 G1 point addition via precompile 0x06
    function _ecAdd(
        uint256[2] memory p1,
        uint256[2] memory p2
    ) internal view returns (uint256[2] memory r) {
        uint256[4] memory input;
        input[0] = p1[0];
        input[1] = p1[1];
        input[2] = p2[0];
        input[3] = p2[1];
        bool success;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            success := staticcall(gas(), 0x06, input, 128, r, 64)
        }
        require(success, "ecAdd failed");
    }

    /// @notice BN254 G1 scalar multiplication via precompile 0x07
    function _ecMul(
        uint256[2] memory p,
        uint256 s
    ) internal view returns (uint256[2] memory r) {
        uint256[3] memory input;
        input[0] = p[0];
        input[1] = p[1];
        input[2] = s;
        bool success;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            success := staticcall(gas(), 0x07, input, 96, r, 64)
        }
        require(success, "ecMul failed");
    }
    
    // ============ Batch Verification ============
    
    /**
     * @notice Verify multiple proofs in a batch (gas efficient)
     * @param evidenceTypes Types of evidence for each proof
     * @param proofs Array of proofs
     * @param allInputs Array of public inputs for each proof
     * @return results Array of verification results
     */
    function batchVerify(
        EvidenceType[] calldata evidenceTypes,
        Proof[] calldata proofs,
        uint256[][] calldata allInputs
    ) external view returns (bool[] memory results) {
        require(
            evidenceTypes.length == proofs.length && 
            proofs.length == allInputs.length,
            "Length mismatch"
        );
        
        results = new bool[](proofs.length);
        
        for (uint256 i = 0; i < proofs.length; i++) {
            // Check nullifier not used
            bytes32 nullifier = keccak256(abi.encodePacked(allInputs[i]));
            if (usedNullifiers[nullifier]) {
                results[i] = false;
                continue;
            }
            
            // Verify proof
            results[i] = _verifyProof(
                evidenceTypes[i],
                proofs[i],
                allInputs[i]
            );
        }
        
        return results;
    }
}
