# Generate docker-compose.validator-fleet.generated.yml with N nodes.
#
# Usage:
#   .\testnet\generate-validator-fleet-compose.ps1
#   .\testnet\generate-validator-fleet-compose.ps1 -NodeCount 10 -Output testnet/docker-compose.validator-fleet.generated.yml

param(
    [int]$NodeCount = 3,
    [string]$Output = ""
)

$ErrorActionPreference = "Stop"
$testnetDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $Output) {
    $Output = Join-Path $testnetDir "docker-compose.validator-fleet.generated.yml"
}
if ($NodeCount -lt 1 -or $NodeCount -gt 10) {
    throw "NodeCount must be 1..10"
}

$apiBase = 28180
$p2pBase = 29100

$lines = @(
    "# AUTO-GENERATED by generate-validator-fleet-compose.ps1 - do not edit by hand",
    "# Regenerate: .\testnet\generate-validator-fleet-compose.ps1 -NodeCount $NodeCount",
    "",
    "x-creg-fleet-common: &creg-fleet-common",
    "  image: creg-node:fleet",
    "  build:",
    "    context: ..",
    "    dockerfile: Dockerfile",
    "  env_file:",
    "    - sepolia-3node.env",
    "  networks:",
    "    - creg-validator-fleet",
    "  restart: unless-stopped",
    "",
    "x-creg-fleet-base-env: &creg-fleet-base-env",
    "  CREG_CHAIN_ID: creg-testnet-1",
    '  CREG_EXPECTED_L1_CHAIN_ID: "11155111"',
    "  CREG_LISTEN: 0.0.0.0:8080",
    "  CREG_DATA_DIR: /data",
    '  CREG_BLOCK_INTERVAL: "5"',
    "  CREG_IPFS_URL: `${CREG_IPFS_URL:?set CREG_IPFS_URL}",
    "  CREG_CHAIN_SPEC_URL: `${CREG_CHAIN_SPEC_URL:?set CREG_CHAIN_SPEC_URL}",
    '  CREG_CHAIN_SPEC_OFFLINE: "false"',
    "  CREG_P2P_LISTEN: /ip4/0.0.0.0/tcp/9000",
    '  CREG_SPEC_SIGNING_PUBKEY: "0437e4adac481519cd6ae66907294c40cfcbf0bdeadd47806f6233be4bd5f82d"',
    "  RUST_LOG: info,chain_registry_node=debug",
    "",
    "services:"
)

$volumeLines = @()

for ($i = 1; $i -le $NodeCount; $i++) {
    $apiPort = $apiBase + $i - 1
    $p2pPort = $p2pBase + $i - 1
    $isValidator = if ($i -le 2) { "true" } else { "false" }
    $nodeId = switch ($i) {
        1 { "core-1" }
        2 { "validator-2" }
        default { "observer-$($i - 2)" }
    }
    $valKey = if ($i -le 2) { "`${CREG_VALIDATOR_KEY_$i}" } else { "" }

    $peerHosts = @()
    $seedHosts = @()
    for ($j = 1; $j -le $NodeCount; $j++) {
        if ($j -eq $i) { continue }
        $peerHosts += "http://creg-node-${j}:8080"
        $seedHosts += "/dns4/creg-node-${j}/tcp/9000"
    }
    $peers = $peerHosts -join ","
    $seeds = $seedHosts -join ","

    $lines += "  creg-node-$i`:"
    $lines += "    <<: *creg-fleet-common"
    $lines += "    container_name: creg-fleet-node$i"
    $lines += "    environment:"
    $lines += "      <<: *creg-fleet-base-env"
    $lines += "      CREG_P2P_SEEDS: $seeds"
    $lines += "      CREG_IS_VALIDATOR: `"$isValidator`""
    if ($i -le 2) {
        $lines += "      CREG_VALIDATOR_KEY: $valKey"
        $lines += "      CREG_OPERATOR_API_KEY: `${CREG_OPERATOR_API_KEY:-docker-dev-operator-key}"
    }
    $lines += "      CREG_NODE_ID: $nodeId"
    $lines += "      CREG_PEERS: $peers"
    if ($i -eq 1) {
        $lines += "      CREG_BRIDGE_KEY: `${CREG_BRIDGE_KEY:-}"
        $lines += '      CREG_TESTNET: "true"'
    }
    $lines += "    ports:"
    $lines += "      - `"`${CREG_3NODE_NODE${i}_API_PORT:-$apiPort}:8080`""
    $lines += "      - `"`${CREG_3NODE_NODE${i}_P2P_PORT:-$p2pPort}:9000`""
    $lines += "    volumes:"
    $lines += "      - fleet-data-$i`:/data"
    $lines += "      - ./chain-spec-cache:/cache:ro"
    if ($i -le 2) {
        $lines += "      - ../rules:/rules:ro"
    }
    if ($i -gt 1) {
        $lines += "    depends_on:"
        $lines += "      creg-node-1:"
        $lines += "        condition: service_started"
    }
    $lines += ""
    $volumeLines += "  fleet-data-$i`:"
}

$lines += "networks:"
$lines += "  creg-validator-fleet:"
$lines += "    driver: bridge"
$lines += ""
$lines += "volumes:"
$lines += $volumeLines

$lines -join "`n" | Set-Content -Path $Output -Encoding utf8
Write-Host "Wrote $Output ($NodeCount nodes, API ports $apiBase-$($apiBase + $NodeCount - 1))"
