# Create or refresh testnet/sepolia-3node.env for the 3-node Sepolia Docker fleet.
#
# Usage:
#   .\testnet\init-sepolia-3node-env.ps1
#   .\testnet\init-sepolia-3node-env.ps1 -RpcUrl "https://sepolia.infura.io/v3/YOUR_KEY"
#   .\testnet\init-sepolia-3node-env.ps1 -Force   # overwrite existing file

param(
    [string]$RpcUrl = "https://ethereum-sepolia-rpc.publicnode.com",
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir
$outPath = Join-Path $scriptDir "sepolia-3node.env"

if ((Test-Path $outPath) -and -not $Force) {
    Write-Host "Already exists: $outPath" -ForegroundColor Yellow
    Write-Host "Re-run with -Force to overwrite, or edit the file manually."
    exit 0
}

# Matches chain-spec.sepolia.json validator core-1 / spec signing pubkey (see finalize-sepolia-spec.ps1).
$key1 = "9d91e9e0d82a02b7be8c40a522d899eea9eeffad244323be3e568973211f3a6d"

$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$bytes = New-Object byte[] 32
$rng.GetBytes($bytes)
$key2 = ([BitConverter]::ToString($bytes) -replace '-', '').ToLower()

Set-Location $repoRoot
$pub1 = (cargo run -q --example ed25519_pubkey_from_secret -p common -- $key1 2>&1 | Select-Object -Last 1).Trim()
$pub2 = (cargo run -q --example ed25519_pubkey_from_secret -p common -- $key2 2>&1 | Select-Object -Last 1).Trim()

$content = @"
# Generated by init-sepolia-3node-env.ps1 — gitignored; safe to edit.
SEPOLIA_RPC_URL=$RpcUrl
CREG_ETH_RPC=$RpcUrl
CREG_3NODE_IPFS_HOST_PORT=15001
CREG_3NODE_SPEC_HOST_PORT=18888
CREG_3NODE_NODE1_API_PORT=28180
CREG_3NODE_NODE1_P2P_PORT=29100
CREG_3NODE_NODE2_API_PORT=28181
CREG_3NODE_NODE2_P2P_PORT=29101
CREG_3NODE_NODE3_API_PORT=28182
CREG_3NODE_NODE3_P2P_PORT=29102

# validator-1: matches chain-spec.sepolia.json core-1 (testnet authority)
CREG_VALIDATOR_KEY_1=$key1

# validator-2: random dev key — NOT in chain-spec unless you register / patch spec
CREG_VALIDATOR_KEY_2=$key2
"@
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outPath, $content, $utf8NoBom)

Write-Host "Wrote $outPath" -ForegroundColor Green
Write-Host ""
Write-Host "Validator pubkeys (for chain-spec / staking):" -ForegroundColor Cyan
Write-Host "  validator-1 (core-1): $pub1"
Write-Host "  validator-2 (local):  $pub2"
Write-Host ""
Write-Host "Next: .\testnet\start-3node-test.ps1" -ForegroundColor Green
Write-Host ""
Write-Host "Note: chain-spec.sepolia.json lists one active validator (core-1)." -ForegroundColor Yellow
Write-Host "Node 2 can boot but may not vote until its pubkey is added to the spec or L1 staking."
