# Prepare Sepolia E2E-301 publish prerequisites (stake + env hints).
# Does NOT publish; prints commands and sets env for run-ops-201-verify.ps1.
#
# Requires: cast (Foundry), Sepolia ETH on publisher EOA, optional IPFS (Kubo).
#
# Usage:
#   .\testnet\prepare-sepolia-publish.ps1 -PublisherKey 0x... -StakeAmountEth 1
#   .\testnet\prepare-sepolia-publish.ps1 -PublisherKeyFile .\my-publisher-eth.key

param(
    [string]$RpcUrl = "https://ethereum-sepolia-rpc.publicnode.com",
    [string]$PublisherKey = "",
    [string]$PublisherKeyFile = "",
    [string]$PublisherAddress = "",
    [double]$StakeAmountEth = 1.0
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir
$specPath = Join-Path $scriptDir "chain-spec.sepolia.json"
if (-not (Test-Path $specPath)) { throw "Missing $specPath" }
$spec = Get-Content $specPath -Raw | ConvertFrom-Json

if ($PublisherKeyFile) {
    $PublisherKey = (Get-Content $PublisherKeyFile -Raw).Trim()
}
if (-not $PublisherKey -and -not $PublisherAddress) {
    throw @"
Set -PublisherKey (0x + 64 hex secp256k1) or -PublisherKeyFile, or -PublisherAddress if already staked.
Do NOT use the literal text 0x<staked_publisher_key> — use a real key or address.
Install cast: .\testnet\install-foundry.ps1 then `$env:PATH = `"`$PWD\testnet\.tools\foundry;`$env:PATH`"
"@
}

$toolsCast = Join-Path $scriptDir ".tools\foundry\cast.exe"
$cast = Get-Command cast -ErrorAction SilentlyContinue
if (-not $cast -and (Test-Path $toolsCast)) {
    $env:PATH = "$(Split-Path $toolsCast);$env:PATH"
    $cast = Get-Command cast -ErrorAction SilentlyContinue
}
if (-not $cast) {
    throw "Foundry cast not on PATH. Run: .\testnet\install-foundry.ps1"
}

function Get-CastWalletAddress {
    param([string]$PrivateKey)
    $prev = $env:FOUNDRY_DISABLE_NIGHTLY_WARNING
    $env:FOUNDRY_DISABLE_NIGHTLY_WARNING = "1"
    try {
        $raw = (& cast wallet address --private-key $PrivateKey 2>&1 | Out-String)
        if ($raw -match '(0x[a-fA-F0-9]{40})') { return $matches[1] }
        throw "Could not derive address from publisher key: $raw"
    } finally {
        if ($null -eq $prev) { Remove-Item Env:FOUNDRY_DISABLE_NIGHTLY_WARNING -ErrorAction SilentlyContinue }
        else { $env:FOUNDRY_DISABLE_NIGHTLY_WARNING = $prev }
    }
}

if ($PublisherAddress) {
    $pubAddr = $PublisherAddress.Trim()
    if ($pubAddr -notmatch '^0x[a-fA-F0-9]{40}$') { throw "Invalid -PublisherAddress" }
} else {
    $pubAddr = Get-CastWalletAddress -PrivateKey $PublisherKey
}

$token = $spec.contracts.creg_token
$staking = $spec.contracts.staking
$wei = [bigint]([math]::Floor($StakeAmountEth * 1e18))

Write-Host ""
Write-Host "=== Sepolia publish prep (E2E-301) ===" -ForegroundColor Cyan
Write-Host "Publisher EOA:  $pubAddr"
Write-Host "Staking:        $staking"
Write-Host "Token:          $token"
Write-Host "RPC:            $RpcUrl"
Write-Host ""

if ($PublisherKeyFile) {
    Write-Host "1) Approve + stake (if not already staked):" -ForegroundColor Yellow
    Write-Host "  .\testnet\stake-publisher-sepolia.ps1 -PublisherKeyFile '$PublisherKeyFile'"
    Write-Host "  (does not print your private key)"
} elseif ($PublisherKey) {
    Write-Host "1) Approve + stake (if not already staked):" -ForegroundColor Yellow
    Write-Host "  Prefer -PublisherKeyFile so the key is not echoed. Or run:"
    Write-Host "  .\testnet\stake-publisher-sepolia.ps1 -PublisherKeyFile <path-to-.key>"
} else {
    Write-Host "1) Skipping stake commands (no -PublisherKey). Ensure $pubAddr is already staked." -ForegroundColor Yellow
}

Write-Host "2) Verify stake:" -ForegroundColor Yellow
Write-Host "cast call $staking `"stakedBalance(address)(uint256)`" $pubAddr --rpc-url $RpcUrl"
Write-Host ""

$pubKeyFile = Join-Path $repoRoot "publisher.key"
Write-Host "3) Ed25519 publish signing key (separate from stake EOA):" -ForegroundColor Yellow
if (Test-Path $pubKeyFile) {
    Write-Host "  OK found $pubKeyFile"
} else {
    Write-Host "  Missing $pubKeyFile — generate from repo root:"
    Write-Host "    cargo run --bin creg -p chain-registry-cli -- keygen publisher"
    Write-Host "  (or .\target\release\creg.exe keygen publisher)"
}
Write-Host ""

Write-Host "4) Set env for publish smoke:" -ForegroundColor Yellow
Write-Host "`$env:CREG_PUBLISHER_ADDRESS = `"$pubAddr`""
Write-Host "`$env:CREG_IPFS_URL = `"http://127.0.0.1:5001`"   # .\testnet\start-ipfs.ps1  OR  ipfs daemon"
Write-Host ""

Write-Host "5) Run OPS verify with publish:" -ForegroundColor Yellow
Write-Host ".\testnet\run-ops-201-verify.ps1 -Force"
Write-Host ""

# Optional: write a local env snippet (gitignored pattern for *.env)
$snippet = Join-Path $scriptDir ".env.publish.local"
@"
# Generated by prepare-sepolia-publish.ps1 - do not commit
CREG_PUBLISHER_ADDRESS=$pubAddr
CREG_IPFS_URL=http://127.0.0.1:5001
"@ | Set-Content -Path $snippet -Encoding utf8
Write-Host "Wrote $snippet (ensure .env.* is gitignored)" -ForegroundColor DarkGray
