# Create a NEW Sepolia CREG faucet wallet + env file. Does not use the lost deployer key.
#
# The old faucet pool (20M CREG at 0xf4c0bdBB681A61Aa0B123E82C04b0d692F53D58e) stays on-chain
# but is deprecated — funds cannot be moved without that private key.
#
# Usage:
#   .\testnet\setup-sepolia-faucet.ps1
#   .\testnet\fund-sepolia-faucet-governance.ps1   # needs governance signer key(s)
#   .\testnet\start-sepolia-faucet.ps1
#   # drip to publisher: open http://localhost:8082 or .\testnet\drip-sepolia-faucet.ps1 -Address 0x...

param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$secretsDir = Join-Path $scriptDir "secrets"
New-Item -ItemType Directory -Force -Path $secretsDir | Out-Null

$keyLatest = Join-Path $secretsDir "faucet-sepolia-latest.key"
$addrLatest = Join-Path $secretsDir "faucet-sepolia-latest.address.txt"
$envFile = Join-Path $scriptDir ".env.sepolia.faucet"

if ((Test-Path $keyLatest) -and (Test-Path $envFile) -and -not $Force) {
    $existing = (Get-Content $addrLatest -Raw).Trim()
    Write-Host "Faucet already set up ($existing). Use -Force to rotate wallet." -ForegroundColor Yellow
    Write-Host "  Env: $envFile"
    & (Join-Path $scriptDir "sync-sepolia-faucet-env.ps1")
    exit 0
}

$bytes = [byte[]]::new(32)
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$hex = "0x" + ([BitConverter]::ToString($bytes) -replace "-", "").ToLower()

$cast = Join-Path $scriptDir ".tools\foundry\cast.exe"
if (-not (Test-Path $cast)) { $cast = (Get-Command cast -ErrorAction Stop).Source }
$env:FOUNDRY_DISABLE_NIGHTLY_WARNING = "1"
$raw = (& $cast wallet address --private-key $hex 2>&1 | Out-String)
if ($raw -notmatch '(0x[a-fA-F0-9]{40})') { throw "Could not derive faucet address" }
$address = $matches[1]

$ts = Get-Date -Format "yyyyMMdd-HHmmss"
$keyFile = Join-Path $secretsDir "faucet-sepolia-$ts.key"
Set-Content -Path $keyFile -Value $hex -Encoding utf8 -NoNewline
Set-Content -Path $keyLatest -Value $hex -Encoding utf8 -NoNewline
Set-Content -Path $addrLatest -Value $address -Encoding utf8
Set-Content -Path (Join-Path $secretsDir "faucet-sepolia-$ts.address.txt") -Value $address -Encoding utf8

try { icacls $keyLatest /inheritance:r /grant:r "${env:USERNAME}:(R,W)" | Out-Null } catch { }

$spec = Get-Content (Join-Path $scriptDir "chain-spec.sepolia.json") -Raw | ConvertFrom-Json
$token = $spec.contracts.creg_token
$rpc = "https://ethereum-sepolia-rpc.publicnode.com"
$deprecated = "0xf4c0bdBB681A61Aa0B123E82C04b0d692F53D58e"

@"
# Sepolia CREG faucet — generated by setup-sepolia-faucet.ps1 (DO NOT COMMIT)
SEPOLIA_RPC_URL=$rpc
FAUCET_PORT=8082
FAUCET_RPC_URL=$rpc
FAUCET_PRIVATE_KEY=$hex
FAUCET_ADDRESS=$address
FAUCET_TOKEN_CONTRACT=$token
FAUCET_CHAIN_ID=11155111
FAUCET_DRIP_AMOUNT=1000000000000000000000
FAUCET_NATIVE_DRIP_AMOUNT=0
FAUCET_COOLDOWN_SECS=300
FAUCET_IP_COOLDOWN_SECS=300
FAUCET_MAX_BALANCE=10000000000000000000000
FAUCET_NATIVE_MAX_BALANCE=0
FAUCET_POW_DISABLED=true
FAUCET_EXPLORER_URL=https://sepolia.etherscan.io
FAUCET_PUBLIC_RPC_URL=$rpc
FAUCET_ADMIN_TOKEN=sepolia-faucet-admin-change-me
RUST_LOG=info,faucet=info
# Deprecated (lost key): $deprecated
"@ | Set-Content -Path $envFile -Encoding utf8

Write-Host ""
Write-Host "=== New Sepolia CREG faucet ===" -ForegroundColor Cyan
Write-Host "Address:     $address" -ForegroundColor Green
Write-Host "Key file:    $keyLatest"
Write-Host "Env file:    $envFile"
Write-Host ""
Write-Host "Deprecated (do not use - key lost):" -ForegroundColor DarkYellow
Write-Host "  $deprecated  (~20M CREG locked on-chain)"
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1) Back up $keyLatest to a password manager"
Write-Host "  2) Fund NEW faucet with Sepolia ETH (gas for drips):"
Write-Host "     .\testnet\fund-sepolia-faucet-eth.ps1"
Write-Host "     (or https://www.alchemy.com/faucets/ethereum-sepolia)"
Write-Host "  3) Mint CREG into the new faucet via governance:"
Write-Host "     .\testnet\fund-sepolia-faucet-governance.ps1"
Write-Host "     (set GOVERNANCE_SIGNER_KEY in testnet\.env.sepolia - must be a governance signer)"
Write-Host "  4) Start faucet:"
Write-Host "     .\testnet\start-sepolia-faucet.ps1"
Write-Host "  5) Drip to your publisher, then stake:"
Write-Host "     .\testnet\drip-sepolia-faucet.ps1 -Address 0x8E468575568756E210caA39D04A24a8bF2266B84"
Write-Host "     .\testnet\stake-publisher-sepolia.ps1 -PublisherKeyFile ... -StakeOnly"
Write-Host ""
