# Chain Registry 3-Node Sepolia Test Orchestrator
# Runs a 3-node fleet (2 validators + observer) against live Ethereum Sepolia.
#
# Prerequisites:
#   - Docker Desktop / Docker Engine running
#   - testnet/sepolia-3node.env (copy from sepolia-3node.env.example)
#   - testnet/chain-spec.sepolia.json.sig present
#
# Usage:
#   .\testnet\start-3node-test.ps1
#   .\testnet\start-3node-test.ps1 -RpcUrl "https://ethereum-sepolia-rpc.publicnode.com"
#   .\testnet\start-3node-test.ps1 -SkipRpcVerify
#   .\testnet\start-3node-test.ps1 -FreshVolumes   # reset Docker volumes (fixes IPFS repo.lock)

param(
    [string]$RpcUrl = "",
    [switch]$SkipRpcVerify,
    [switch]$FreshVolumes,
    [switch]$Sandbox
)

$ErrorActionPreference = "Stop"

$Script:SepoliaFallbackRpcUrls = @(
    "https://ethereum-sepolia-rpc.publicnode.com",
    "https://rpc.ankr.com/eth_sepolia",
    "https://1rpc.io/sepolia"
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir
Set-Location $repoRoot

$composeFile = Join-Path $scriptDir "docker-compose.3node.yml"
$composeSandboxFile = Join-Path $scriptDir "docker-compose.3node-sandbox.yml"
function Get-ComposeArgs {
    param([string[]]$Extra)
    $args = @("-f", $composeFile)
    if ($Sandbox) { $args += @("-f", $composeSandboxFile) }
    if (Test-Path $fleetEnv) { $args += @("--env-file", $fleetEnv) }
    if ($Extra) { $args += $Extra }
    return $args
}
$fleetEnv = Join-Path $scriptDir "sepolia-3node.env"
$fleetEnvExample = Join-Path $scriptDir "sepolia-3node.env.example"
$legacySepoliaEnv = Join-Path $scriptDir ".env.sepolia"
$specPath = Join-Path $scriptDir "chain-spec.sepolia.json"
$sigPath = Join-Path $scriptDir "chain-spec.sepolia.json.sig"

function Write-Step($msg) {
    Write-Host ""
    Write-Host "=== $msg ===" -ForegroundColor Cyan
}

function Write-Success($msg) {
    Write-Host "✓ $msg" -ForegroundColor Green
}

function Write-Warn($msg) {
    Write-Host "⚠ $msg" -ForegroundColor Yellow
}

function Import-DotEnvFile {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return }
    Get-Content $Path | ForEach-Object {
        $line = $_.Trim()
        if ($line -eq "" -or $line.StartsWith("#")) { return }
        if ($line -match '^([^=]+)=(.*)$') {
            $key = $matches[1].Trim()
            $val = $matches[2].Trim()
            if ($val.StartsWith('"') -and $val.EndsWith('"')) {
                $val = $val.Substring(1, $val.Length - 2)
            }
            Set-Item -Path "Env:$key" -Value $val
        }
    }
}

function Write-FleetEnvFile {
    param(
        [string]$Rpc,
        [string]$Key1,
        [string]$Key2
    )
    @(
        "# Auto-generated by start-3node-test.ps1 - edit or replace with sepolia-3node.env.example copy"
        "SEPOLIA_RPC_URL=$Rpc"
        "CREG_ETH_RPC=$Rpc"
        "CREG_VALIDATOR_KEY_1=$Key1"
        "CREG_VALIDATOR_KEY_2=$Key2"
    ) | Set-Content -Path $fleetEnv -Encoding utf8
}

function Merge-SepoliaEnv {
    if (Test-Path $fleetEnv) {
        Import-DotEnvFile -Path $fleetEnv
        Write-Success "Loaded $fleetEnv"
        return
    }
    if (Test-Path $legacySepoliaEnv) {
        Write-Warn "sepolia-3node.env missing; merging from .env.sepolia"
        Import-DotEnvFile -Path $legacySepoliaEnv
        if (-not $env:CREG_ETH_RPC -and $env:SEPOLIA_RPC_URL) {
            $env:CREG_ETH_RPC = $env:SEPOLIA_RPC_URL
        }
        if (-not $env:CREG_VALIDATOR_KEY_1 -and $env:CREG_VALIDATOR_KEY) {
            $env:CREG_VALIDATOR_KEY_1 = $env:CREG_VALIDATOR_KEY
        }
        if ($env:CREG_ETH_RPC -and $env:CREG_VALIDATOR_KEY_1 -and $env:CREG_VALIDATOR_KEY_2) {
            Write-FleetEnvFile -Rpc $env:CREG_ETH_RPC -Key1 $env:CREG_VALIDATOR_KEY_1 -Key2 $env:CREG_VALIDATOR_KEY_2
            Write-Success "Wrote $fleetEnv from .env.sepolia for docker compose env_file"
        }
        return
    }
    Write-Error @"
Missing fleet env file. Create it from the example:
  Copy-Item '$fleetEnvExample' '$fleetEnv'
Then set SEPOLIA_RPC_URL, CREG_ETH_RPC, CREG_VALIDATOR_KEY_1, and CREG_VALIDATOR_KEY_2.
"@
}

function Test-RpcUrlPlaceholder {
    param([string]$Url)
    return ($Url -match 'YOUR_|REPLACE|example\.com|/v3/$')
}

function Invoke-EthJsonRpc {
    param(
        [string]$RpcUrl,
        [string]$Method,
        [object[]]$Params = @(),
        [int]$TimeoutSec = 45
    )
    $body = @{
        jsonrpc = "2.0"
        method  = $Method
        params  = $Params
        id      = 1
    } | ConvertTo-Json -Compress
    return Invoke-RestMethod -Uri $RpcUrl -Method Post -Body $body -ContentType "application/json" -TimeoutSec $TimeoutSec
}

function Test-SepoliaRpc {
    param(
        [string]$RpcUrl,
        [int]$TimeoutSec = 45,
        [int]$Retries = 3
    )
    $lastError = $null
    for ($attempt = 1; $attempt -le $Retries; $attempt++) {
        try {
            $resp = Invoke-EthJsonRpc -RpcUrl $RpcUrl -Method "eth_chainId" -TimeoutSec $TimeoutSec
            if (-not $resp.result) {
                throw "eth_chainId returned no result"
            }
            $chainId = [Convert]::ToInt64($resp.result, 16)
            if ($chainId -ne 11155111) {
                throw "reported chain_id $chainId (expected 11155111)"
            }
            return
        } catch {
            $lastError = $_.Exception.Message
            if ($attempt -lt $Retries) {
                Write-Warn "RPC attempt $attempt/$Retries failed for $RpcUrl - retrying..."
                Start-Sleep -Seconds 2
            }
        }
    }
    throw "RPC $RpcUrl failed after $Retries attempts: $lastError"
}

function Resolve-SepoliaRpc {
    param([string]$PreferredUrl)
    if (Test-RpcUrlPlaceholder -Url $PreferredUrl) {
        throw @"
CREG_ETH_RPC looks like a template URL: $PreferredUrl
Set a real Sepolia endpoint in testnet/sepolia-3node.env, or run:
  .\testnet\init-sepolia-3node-env.ps1 -Force
  .\testnet\start-3node-test.ps1 -RpcUrl `"https://ethereum-sepolia-rpc.publicnode.com`"
"@
    }
    try {
        Test-SepoliaRpc -RpcUrl $PreferredUrl
        return $PreferredUrl
    } catch {
        Write-Warn "Primary RPC failed: $($_.Exception.Message)"
    }
    foreach ($fallback in $Script:SepoliaFallbackRpcUrls) {
        if ($fallback -eq $PreferredUrl) { continue }
        Write-Warn "Trying fallback RPC: $fallback"
        try {
            Test-SepoliaRpc -RpcUrl $fallback
            Write-Warn "Using fallback RPC for this run: $fallback"
            return $fallback
        } catch {
            Write-Warn "Fallback failed: $($_.Exception.Message)"
        }
    }
    throw "No working Sepolia RPC. Edit CREG_ETH_RPC in sepolia-3node.env or pass -RpcUrl."
}

function Wait-ComposeHealthy {
    param(
        [string]$ContainerName,
        [int]$MaxSec = 120
    )
    $deadline = (Get-Date).AddSeconds($MaxSec)
    while ((Get-Date) -lt $deadline) {
        $status = docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' $ContainerName 2>$null
        if ($status -eq "healthy" -or $status -eq "running") {
            return $true
        }
        Start-Sleep -Seconds 2
    }
    return $false
}

# Step 0: Pre-flight checks
Write-Step "Pre-flight checks"

try {
    docker info >$null 2>&1
    Write-Success "Docker is running"
} catch {
    Write-Error "Docker is not running. Start Docker Desktop and try again."
}

Merge-SepoliaEnv

if (-not $env:CREG_3NODE_IPFS_HOST_PORT) {
    $env:CREG_3NODE_IPFS_HOST_PORT = "15001"
}
if (-not $env:CREG_3NODE_SPEC_HOST_PORT) {
    $env:CREG_3NODE_SPEC_HOST_PORT = "18888"
}
foreach ($pair in @(
    @("CREG_3NODE_NODE1_API_PORT", "28180"),
    @("CREG_3NODE_NODE1_P2P_PORT", "29100"),
    @("CREG_3NODE_NODE2_API_PORT", "28181"),
    @("CREG_3NODE_NODE2_P2P_PORT", "29101"),
    @("CREG_3NODE_NODE3_API_PORT", "28182"),
    @("CREG_3NODE_NODE3_P2P_PORT", "29102")
)) {
    if (-not (Get-Item -Path "Env:$($pair[0])" -ErrorAction SilentlyContinue).Value) {
        Set-Item -Path "Env:$($pair[0])" -Value $pair[1]
    }
}

if (-not $env:CREG_ETH_RPC) {
    if ($env:SEPOLIA_RPC_URL) {
        $env:CREG_ETH_RPC = $env:SEPOLIA_RPC_URL
    } else {
        Write-Error "CREG_ETH_RPC (or SEPOLIA_RPC_URL) must be set in sepolia-3node.env"
    }
}

foreach ($key in @("CREG_VALIDATOR_KEY_1", "CREG_VALIDATOR_KEY_2")) {
    $val = (Get-Item -Path "Env:$key" -ErrorAction SilentlyContinue).Value
    if (-not $val -or $val -match 'REPLACE|YOUR_INFURA') {
        Write-Host ""
        Write-Host "Fleet env still has placeholders in $fleetEnv" -ForegroundColor Yellow
        Write-Host "Run:  .\testnet\init-sepolia-3node-env.ps1" -ForegroundColor Yellow
        Write-Host "Or edit SEPOLIA_RPC_URL, CREG_ETH_RPC, CREG_VALIDATOR_KEY_1, CREG_VALIDATOR_KEY_2" -ForegroundColor Yellow
        Write-Error "$key must be a 32-byte Ed25519 seed hex (not a placeholder)"
    }
}
if ($RpcUrl) {
    $env:CREG_ETH_RPC = $RpcUrl
    $env:SEPOLIA_RPC_URL = $RpcUrl
}

if (Test-RpcUrlPlaceholder -Url $env:CREG_ETH_RPC) {
    Write-Host "Run:  .\testnet\init-sepolia-3node-env.ps1 -Force" -ForegroundColor Yellow
    Write-Host "Or:   .\testnet\start-3node-test.ps1 -RpcUrl `"https://ethereum-sepolia-rpc.publicnode.com`"" -ForegroundColor Yellow
    Write-Error "CREG_ETH_RPC is still a template URL: $($env:CREG_ETH_RPC)"
}

if (-not $SkipRpcVerify) {
    Write-Step "Verifying Sepolia RPC (eth_chainId == 11155111)"
    try {
        $resolvedRpc = Resolve-SepoliaRpc -PreferredUrl $env:CREG_ETH_RPC
        $env:CREG_ETH_RPC = $resolvedRpc
        $env:SEPOLIA_RPC_URL = $resolvedRpc
        if (Test-Path $fleetEnv) {
            $lines = Get-Content $fleetEnv
            $lines = $lines | ForEach-Object {
                if ($_ -match '^\s*SEPOLIA_RPC_URL\s*=') { "SEPOLIA_RPC_URL=$resolvedRpc" }
                elseif ($_ -match '^\s*CREG_ETH_RPC\s*=') { "CREG_ETH_RPC=$resolvedRpc" }
                else { $_ }
            }
            $lines | Set-Content -Path $fleetEnv -Encoding utf8
        }
        Write-Success "Sepolia RPC OK: $resolvedRpc"
    } catch {
        Write-Error $_.Exception.Message
    }
} else {
    Write-Warn "Skipping Sepolia RPC verification (-SkipRpcVerify)"
}

if (-not (Test-Path $specPath)) {
    Write-Error "Missing $specPath"
}
if (-not (Test-Path $sigPath)) {
    Write-Error "Missing $sigPath - run .\testnet\finalize-sepolia-spec.ps1 or copy a signed spec"
}
Write-Success "Signed Sepolia chain spec present"

# Step 1: Clean up previous test runs (keep volumes unless -FreshVolumes passed later)
Write-Step "Cleaning up previous test runs"
$downArgs = @(Get-ComposeArgs @("down", "--remove-orphans"))
if ($FreshVolumes) {
    $downArgs += "-v"
    Write-Warn "FreshVolumes: removing named volumes (ipfs-data, creg-data-*)"
}
docker compose @downArgs 2>$null
Write-Success "Previous containers removed"

# Step 2: Ensure spec-server mount files are current, start infrastructure
Write-Step "Verifying chain-spec.sepolia.json for spec-server mounts"
if (-not (Test-Path (Join-Path $scriptDir "chain-spec.sepolia.json"))) {
    Write-Error "chain-spec.sepolia.json missing under testnet/"
}
Write-Success "Signed Sepolia chain spec ready for nginx bind mounts"


function Invoke-IpfsVolumePerms {
    param([string[]]$ComposeArgs)
    Write-Host "Running ipfs-perms (chown 1000:100, clear stale repo.lock)..." -ForegroundColor DarkGray
    $permsArgs = $ComposeArgs + @("run", "--rm", "--no-deps", "ipfs-perms")
    docker compose @permsArgs
    if ($LASTEXITCODE -ne 0) {
        Write-Error @"
ipfs-perms failed. IPFS Kubo needs uid 1000 on the volume.
Try:  .\testnet\start-3node-test.ps1 -FreshVolumes
Or:   docker volume rm testnet_ipfs-data
"@
    }
}
Write-Step "Starting infrastructure (IPFS, spec-server)"
Invoke-IpfsVolumePerms -ComposeArgs @(Get-ComposeArgs)
docker compose @(Get-ComposeArgs @("up", "-d", "ipfs", "spec-server"))
if ($LASTEXITCODE -ne 0) {
    Write-Error "docker compose failed to start infrastructure"
}

if (-not (Wait-ComposeHealthy -ContainerName "creg-3node-ipfs" -MaxSec 180)) {
    docker compose -f $composeFile logs --tail 40 ipfs ipfs-perms | Write-Host
    Write-Host ""
    Write-Host "If you see 'repo.lock: permission denied', reset IPFS data:" -ForegroundColor Yellow
    Write-Host "  .\testnet\start-3node-test.ps1 -FreshVolumes" -ForegroundColor Yellow
    Write-Error "IPFS container did not become healthy"
}
Write-Success "IPFS ready"

$specHostPort = if ($env:CREG_3NODE_SPEC_HOST_PORT) { $env:CREG_3NODE_SPEC_HOST_PORT } else { "18888" }
$specUrl = "http://localhost:$specHostPort/chain-spec.json"
$specReady = $false
$specDeadline = (Get-Date).AddSeconds(60)
while ((Get-Date) -lt $specDeadline) {
    if ((docker inspect --format '{{.State.Health.Status}}' creg-3node-spec-server 2>$null) -eq "healthy") {
        $specReady = $true
        break
    }
    try {
        $probe = Invoke-WebRequest -Uri $specUrl -UseBasicParsing -TimeoutSec 5
        if ($probe.StatusCode -eq 200 -and $probe.Content -match '"chain_id"') {
            $specReady = $true
            break
        }
    } catch { }
    Start-Sleep -Seconds 2
}
if (-not $specReady) {
    docker compose -f $composeFile logs --tail 20 spec-server | Write-Host
    Write-Error "spec-server did not become healthy (probe: $specUrl)"
}
Write-Success "spec-server ready at http://localhost:$specHostPort/chain-spec.json"

# Step 3: Build and start the 3 nodes
if ($Sandbox) {
    Write-Step "SANDBOX-301: using chain-registry-node-secure:latest (run build-3node-secure-image first)"
    $secureBuild = Join-Path $scriptDir "build-3node-secure-image.ps1"
    if (Test-Path $secureBuild) {
        & $secureBuild -SkipAppBuild
        if ($LASTEXITCODE -ne 0) { Write-Error "Secure image build failed" }
    } else {
        docker image inspect chain-registry-node-secure:latest 2>$null | Out-Null
        if ($LASTEXITCODE -ne 0) {
            Write-Error "Missing chain-registry-node-secure:latest — run .\testnet\build-3node-secure-image.ps1"
        }
    }
} else {
    Write-Step "Building node image (Dockerfile.windows)"
    docker compose @(Get-ComposeArgs) build creg-node-1
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Node image build failed. See Docker output above."
    }
}

Write-Step "Starting 3 Chain Registry nodes"
$upArgs = @(Get-ComposeArgs) + @("up", "-d")
if ($Sandbox) { $upArgs += "--no-build" }
$upArgs += @("creg-node-1", "creg-node-2", "creg-node-3")
docker compose @upArgs

Write-Host ""
Write-Host "Waiting for nodes to boot (chain-spec fetch + Sepolia L1 sync)..." -ForegroundColor Cyan
Start-Sleep -Seconds 15

# Step 4: Health checks
Write-Step "Health checks"

$node1ApiPort = if ($env:CREG_3NODE_NODE1_API_PORT) { $env:CREG_3NODE_NODE1_API_PORT } else { "28180" }
try {
    $r = Invoke-WebRequest -Uri "http://localhost:$node1ApiPort/v1/health" -UseBasicParsing -TimeoutSec 10
    Write-Success "Node 1 health check: $($r.StatusCode)"
} catch {
    Write-Warn "Node 1 health check failed (may still be booting - check logs)"
}

Write-Host ""
Write-Host "=== 3-Node Sepolia Test Started ===" -ForegroundColor Green
Write-Host "Services:"
Write-Host "  Sepolia RPC:     $($env:CREG_ETH_RPC)"
$ipfsHostPort = if ($env:CREG_3NODE_IPFS_HOST_PORT) { $env:CREG_3NODE_IPFS_HOST_PORT } else { "15001" }
Write-Host "  IPFS API:        http://localhost:$ipfsHostPort"
$specHostPort = if ($env:CREG_3NODE_SPEC_HOST_PORT) { $env:CREG_3NODE_SPEC_HOST_PORT } else { "18888" }
Write-Host "  Spec Server:     http://localhost:$specHostPort/chain-spec.json"
$node2ApiPort = if ($env:CREG_3NODE_NODE2_API_PORT) { $env:CREG_3NODE_NODE2_API_PORT } else { "28181" }
$node3ApiPort = if ($env:CREG_3NODE_NODE3_API_PORT) { $env:CREG_3NODE_NODE3_API_PORT } else { "28182" }
Write-Host "  Node 1 API:      http://localhost:$node1ApiPort"
Write-Host "  Node 2 API:      http://localhost:$node2ApiPort"
Write-Host "  Node 3 API:      http://localhost:$node3ApiPort"
Write-Host ""
Write-Host "P2P seeds use placeholder peer IDs until updated from node logs (see OPERATOR.md)."
Write-Host ""
Write-Host "Logs:"
Write-Host "  docker compose -f $composeFile logs -f"
Write-Host ""
Write-Host "Soak:"
Write-Host "  .\testnet\soak-3node-consensus.ps1"
Write-Host ""
Write-Host "Stop:"
Write-Host "  docker compose -f $composeFile down"
